spring:
  data:
    mongodb:
      uri: mongodb+srv://saininishchay:nishu123@cluster0.jexok.mongodb.net/test
      database: TweetApp
  application:
    name: TweetAppService
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: tweetApp
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 100000
      
logging:
  file:
    path: './config/logs'
    name: ${logging.file.path}/my-app.log
  level:
    org.springframework.web: ERROR
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
client:
  url: http://localhost:4200

server:
  port: 8082
